"""Создание моделей

Revision ID: 66db1804e026
Revises: d324b4a761fd
Create Date: 2025-09-28 22:16:16.277968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66db1804e026'
down_revision: Union[str, None] = 'd324b4a761fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'games', ['sid'])
    op.drop_column('games', 'board')
    op.add_column('moves', sa.Column('position_x', sa.Integer(), nullable=False))
    op.add_column('moves', sa.Column('position_y', sa.Integer(), nullable=False))
    op.add_column('moves', sa.Column('value', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'moves', ['sid'])
    op.drop_column('moves', 'position')
    op.create_unique_constraint(None, 'players', ['sid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='unique')
    op.add_column('moves', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'moves', type_='unique')
    op.drop_column('moves', 'value')
    op.drop_column('moves', 'position_y')
    op.drop_column('moves', 'position_x')
    op.add_column('games', sa.Column('board', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'games', type_='unique')
    # ### end Alembic commands ###
