"""Создание моделей

Revision ID: 99873d0a1c7d
Revises: 
Create Date: 2025-09-27 16:44:01.620923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99873d0a1c7d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('sid'),
    sa.UniqueConstraint('sid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('games',
    sa.Column('player1_sid', sa.UUID(), nullable=False),
    sa.Column('player2_sid', sa.UUID(), nullable=True),
    sa.Column('board', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'active', 'finished', name='gamestatus'), nullable=False),
    sa.Column('winner_sid', sa.UUID(), nullable=True),
    sa.Column('current_turn_sid', sa.UUID(), nullable=True),
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['current_turn_sid'], ['players.sid'], ),
    sa.ForeignKeyConstraint(['player1_sid'], ['players.sid'], ),
    sa.ForeignKeyConstraint(['player2_sid'], ['players.sid'], ),
    sa.ForeignKeyConstraint(['winner_sid'], ['players.sid'], ),
    sa.PrimaryKeyConstraint('sid'),
    sa.UniqueConstraint('sid')
    )
    op.create_table('moves',
    sa.Column('game_sid', sa.UUID(), nullable=False),
    sa.Column('player_sid', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['game_sid'], ['games.sid'], ),
    sa.ForeignKeyConstraint(['player_sid'], ['players.sid'], ),
    sa.PrimaryKeyConstraint('sid'),
    sa.UniqueConstraint('sid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moves')
    op.drop_table('games')
    op.drop_table('players')
    # ### end Alembic commands ###
